name: Build and Release ai-shell

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'
  workflow_dispatch:  # Manual trigger also allowed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Ensure version consistency
        with:
          name: ai-shell-deb  # The name of the artifact as it will appear in the workflow
          path: release/ai-shell_*.deb  # Full path to the .deb file in the release folder

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v3  # Consistent version with upload-artifact
        with:
          name: ai-shell-deb  # Matches the name given in upload-artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/ai-shell_*.deb  # Full path to the downloaded .deb artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
