name: Build and Release ai-shell

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'
  workflow_dispatch:  # Manual trigger also allowed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: List files in release directory
        run: ls -l release/  # Debugging step to verify the .deb file

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ai-shell-deb
          path: release/ai-shell_*.deb  # Path to the .deb file in the release folder

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ai-shell-deb  # Download the artifact uploaded in the build job

      - name: Verify downloaded artifact
        run: ls -l  # Verify the downloaded artifact is available

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/ai-shell_*.deb  # Ensure this points to the downloaded artifact location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
