name: Build and Release ai-shell

on:
  push:
    branches:
      - main
    paths:
      - '**/*.sh'
      - '**/*.deb'
      - 'ai-shell/**'
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: ai-shell-deb
          path: ai-shell.deb
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ai-shell.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
