name: Build and Release ai-shell

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'
  workflow_dispatch:  # Manual trigger also allowed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: List files in release directory
        run: ls -l release/  # Lists files in release directory to verify the .deb file presence

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: ai-shell-deb
          path: release/ai-shell_*.deb  # Ensure this matches the correct path

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ai-shell-deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/ai-shell_*.deb  # Ensure this matches the downloaded artifact location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
